"use client";
export default function Head() {
  return (
    <>
      <title>amnei Next Ad</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
